from abc import ABC, abstractmethod
from uuid import UUID


class IImageStorage(ABC):
    @abstractmethod
    async def save_temp(self, image_id: UUID, data: bytes) -> None: ...
    @abstractmethod
    def get_temp_path(self, image_id: UUID) -> str: ...
    @abstractmethod
    async def move_to_permanent_storage(self, image_id: UUID) -> None: ...
    @abstractmethod
    async def get_permanent_path(self, image_id: UUID) -> str: ...
    @abstractmethod
    async def delete(self, path: str) -> None: ...
    @abstractmethod
    async def get_image_as_png_bytes(self, path: str) -> bytes: ...
