from abc import ABC, abstractmethod
from uuid import UUID

from app.map.entity.polygon import Polygon


class IAreaRepository(ABC):
    @abstractmethod
    async def add(self, polygon: Polygon) -> None: ...
    @abstractmethod
    async def find_by_id(self, polygon_id: UUID) -> Polygon | None: ...
    @abstractmethod
    async def find_by_user(self, user_id: UUID) -> list[Polygon]: ...
    @abstractmethod
    async def update(self, polygon: Polygon) -> None: ...
    @abstractmethod
    async def delete(self, polygon_id: UUID) -> None: ...
    @abstractmethod
    async def exists_with_name(self, user_id: UUID, name: str, exclude_id: UUID | None = None) -> bool: ...
    @abstractmethod
    async def count_by_user(self, user_id: UUID) -> int: ...
