from abc import ABC, abstractmethod

from app.user.entity.group import Group


class IGroupRepository(ABC):
    @abstractmethod
    async def save(self, name: str) -> None: ...
    @abstractmethod
    async def find_by_id(self, group_id: int) -> Group | None: ...
    @abstractmethod
    async def find_by_name(self, name: str) -> Group | None: ...
    @abstractmethod
    async def find_all(self, skip: int, limit: int) -> list[Group]: ...
    @abstractmethod
    async def update(self, group: Group) -> None: ...
    @abstractmethod
    async def delete(self, group_id: int) -> None: ...
    @abstractmethod
    async def upsert(self, group_id: int, name: str) -> None: ...
